/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_roboo_like_netease_jni_JniClient.h"
#include <stdio.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_roboo_like_netease_jni_JniClient
 * Method:    addStr
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_roboo_like_netease_jni_JniClient_addStr
  (JNIEnv *env, jclass obj, jstring strA, jstring strB)
{
	jstring str = (*env)->NewStringUTF(env,"Hello World from JNI");
	return str;
}

/*
 * Class:     com_roboo_like_netease_jni_JniClient
 * Method:    addInt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_roboo_like_netease_jni_JniClient_addInt
  (JNIEnv *env, jclass obj , jint a, jint b)
{
	return a+b;
}

#ifdef __cplusplus
}
#endif
